In [1]:
import pandas as pd

In [3]:
!pip install pycaret

Requirement already satisfied: pycaret in .\anaconda3\envs\pycaret_env\lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (8.37.0)
Requirement already satisfied: ipywidgets>=7.6.5 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (8.1.9)
Requirement already satisfied: tqdm>=4.62.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (4.70.0)
Requirement already satisfied: numpy<1.27,>=1.21 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: scikit-learn>1.4.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (2.0.6)
Requirement already satisfied: imbalanced-learn>=0.12.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.14.2)
Requirement already satisfied: category-encoders>=2.4.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (2.6.3)
Requirement already satisfied: lightgbm>=3.0.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (4.7.0)
Requirement already satisfied: numba>=0.55.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.61.2)
Requirement already satisfied: requests>=2.27.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (2.34.2)
Requirement already satisfied: psutil>=5.9.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (7.2.2)
Requirement already satisfied: markupsafe>=2.0.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (3.0.3)
Requirement already satisfied: importlib_metadata>=4.12.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (9.0.1)
Requirement already satisfied: nbformat>=4.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (5.11.1)
Requirement already satisfied: cloudpickle in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (4.0.1)
Requirement already satisfied: matplotlib<3.8.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (3.7.5)
Requirement already satisfied: scikit-plot>=0.3.7 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (6.3.0)
Requirement already satisfied: kaleido>=0.2.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.2.1)
Requirement already satisfied: schemdraw==0.15 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.15.0)
Requirement already satisfied: sktime==0.26.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in .\anaconda3\envs\pycaret_env\lib\site-packages (from sktime==0.26.0->pycaret) (26.3)
Requirement already satisfied: scikit-base<0.8.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: contourpy>=1.0.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.3.1)
Requirement already satisfied: cycler>=0.10 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.63.0)
Requirement already satisfied: kiwisolver>=1.0.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.5.0)
Requirement already satisfied: pillow>=6.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (12.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\anaconda3\envs\pycaret_env\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pandas<2.2.0->pycaret) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pandas<2.2.0->pycaret) (2026.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from scikit-learn>1.4.0->pycaret) (3.5.0)
Requirement already satisfied: patsy>=0.5.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.2)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in .\anaconda3\envs\pycaret_env\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (0.1.6)
Requirement already satisfied: zipp>=3.20 in .\anaconda3\envs\pycaret_env\lib\site-packages (from importlib_metadata>=4.12.0->pycaret) (4.1.0)
Requirement already satisfied: colorama in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: decorator in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (5.3.1)
Requirement already satisfied: exceptiongroup in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (1.3.1)
Requirement already satisfied: jedi>=0.16 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (0.20.0)
Requirement already satisfied: matplotlib-inline in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.53)
Requirement already satisfied: pygments>=2.4.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (2.21.0)
Requirement already satisfied: stack_data in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (5.16.1)
Requirement already satisfied: typing_extensions>=4.6 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipython>=5.5.0->pycaret) (4.16.0)
Requirement already satisfied: wcwidth>=0.1.4 in .\anaconda3\envs\pycaret_env\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: comm>=0.1.3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.16 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in .\anaconda3\envs\pycaret_env\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.17)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in .\anaconda3\envs\pycaret_env\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.7)
Requirement already satisfied: narwhals>=1.15 in .\anaconda3\envs\pycaret_env\lib\site-packages (from lightgbm>=3.0.0->pycaret) (2.23.0)
Requirement already satisfied: fastjsonschema>=2.15 in .\anaconda3\envs\pycaret_env\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in .\anaconda3\envs\pycaret_env\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in .\anaconda3\envs\pycaret_env\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.9.1)
Requirement already satisfied: attrs>=22.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in .\anaconda3\envs\pycaret_env\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in .\anaconda3\envs\pycaret_env\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in .\anaconda3\envs\pycaret_env\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=4.2.0->pycaret) (4.11.5)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from numba>=0.55.0->pycaret) (0.44.0)
Requirement already satisfied: dash>=2.11.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.14.2)
Requirement already satisfied: orjson<4.0.0,>=3.10.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.11.9)
Requirement already satisfied: tsdownsample>=0.1.3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.5.1)
Requirement already satisfied: Flask<3.1,>=1.0.4 in .\anaconda3\envs\pycaret_env\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in .\anaconda3\envs\pycaret_env\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.0.6)
Requirement already satisfied: retrying in .\anaconda3\envs\pycaret_env\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.3.3)
Requirement already satisfied: ansi2html in .\anaconda3\envs\pycaret_env\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.5)
Requirement already satisfied: nest-asyncio in .\anaconda3\envs\pycaret_env\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.0)
Requirement already satisfied: setuptools in .\anaconda3\envs\pycaret_env\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (83.0.0)
Requirement already satisfied: itsdangerous>=2.1.2 in .\anaconda3\envs\pycaret_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: click>=8.1.3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.5.0)
Requirement already satisfied: blinker>=1.6.2 in .\anaconda3\envs\pycaret_env\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.9)
Requirement already satisfied: urllib3 in .\anaconda3\envs\pycaret_env\lib\site-packages (from pmdarima>=2.0.4->pycaret) (2.7.0)
Requirement already satisfied: six>=1.5 in .\anaconda3\envs\pycaret_env\lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\anaconda3\envs\pycaret_env\lib\site-packages (from requests>=2.27.1->pycaret) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in .\anaconda3\envs\pycaret_env\lib\site-packages (from requests>=2.27.1->pycaret) (3.19)
Requirement already satisfied: certifi>=2023.5.7 in .\anaconda3\envs\pycaret_env\lib\site-packages (from requests>=2.27.1->pycaret) (2026.7.22)
Requirement already satisfied: formulaic>=1.1.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from statsmodels>=0.12.1->pycaret) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.12.1->pycaret) (2.0.1)
Requirement already satisfied: wrapt>=1.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from formulaic>=1.1.0->statsmodels>=0.12.1->pycaret) (2.2.1)
Requirement already satisfied: executing>=1.2.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from stack_data->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\anaconda3\envs\pycaret_env\lib\site-packages (from stack_data->ipython>=5.5.0->pycaret) (3.0.2)
Requirement already satisfied: pure_eval in .\anaconda3\envs\pycaret_env\lib\site-packages (from stack_data->ipython>=5.5.0->pycaret) (0.2.3)

In [4]:
!pip install flaml

Requirement already satisfied: flaml in .\anaconda3\envs\pycaret_env\lib\site-packages (2.7.0)
Requirement already satisfied: NumPy>=1.17 in .\anaconda3\envs\pycaret_env\lib\site-packages (from flaml) (1.26.4)

In [5]:
# Load the CSV file into a DataFrame
df = pd.read_csv('finalNew.csv')

# View the first 5 rows
print(df.head())
df

       Date_x      Close       High        Low       Open     Volume  \
0  2023-05-01  28.818560  28.966092  27.692135  27.751944  570329000
1  2023-06-01  39.644203  39.923316  38.218726  38.367253  635873000
2  2023-07-03  42.283222  42.766739  42.072869  42.386904  198209000
3  2023-08-01  46.364693  46.756492  45.886162  46.317836  237858000
4  2023-09-01  48.360565  49.647615  47.994688  49.609733  463830000

     Close_l    Close_2  Rolling_mean_3_x  Rolling_std_3_x  ...  return_y  \
0  27.661232  27.139885         27.873226         0.859182  ... -0.191382
1  37.714336  39.984123         39.114221         1.224191  ...  0.144186
2  42.172554  40.697086         41.717621         0.885539  ... -0.063589
3  46.586018  46.606956         46.519222         0.134235  ... -0.126332
4  49.203987  49.113262         48.892605         0.462987  ...  0.097744

   Year_y  Month_y  Log_Close Log_Value boxcox_Close  Diff_Close  Diff_Value  \
0    2023        5   3.361020  2.297170     6.303270    0.942011       1.140
1    2023        6   3.679945  2.509599     7.366221   10.825644       2.354
2    2023        7   3.744390  2.374906     7.595449    2.639019      -1.550
3    2023        8   3.836538  2.440606     7.932109    4.081470       0.730
4    2023        9   3.878685  2.575661     8.089660    1.995872       1.660

   Seasonal_Diff_Close  Seasonal_Diff_Value
0             9.365526               -2.664
1            21.399199                0.200
2            27.816617               -0.050
3            27.995302               -0.040
4            34.477687               -0.630

[5 rows x 32 columns]

,Date_x,Close,High,Low,Open,Volume,Close_l,Close_2,Rolling_mean_3_x,Rolling_std_3_x,...,return_y,Year_y,Month_y,Log_Close,Log_Value,boxcox_Close,Diff_Close,Diff_Value,Seasonal_Diff_Close,Seasonal_Diff_Value
0,2023-05-01,28.818560,28.966092,27.692135,27.751944,570329000,27.661232,27.139885,27.873226,0.859182,...,-0.191382,2023,5,3.361020,2.297170,6.303270,0.942011,1.140,9.365526,-2.664
1,2023-06-01,39.644203,39.923316,38.218726,38.367253,635873000,37.714336,39.984123,39.114221,1.224191,...,0.144186,2023,6,3.679945,2.509599,7.366221,10.825644,2.354,21.399199,0.200
2,2023-07-03,42.283222,42.766739,42.072869,42.386904,198209000,42.172554,40.697086,41.717621,0.885539,...,-0.063589,2023,7,3.744390,2.374906,7.595449,2.639019,-1.550,27.816617,-0.050
3,2023-08-01,46.364693,46.756492,45.886162,46.317836,237858000,46.586018,46.606956,46.519222,0.134235,...,-0.126332,2023,8,3.836538,2.440606,7.932109,4.081470,0.730,27.995302,-0.040
4,2023-09-01,48.360565,49.647615,47.994688,49.609733,463830000,49.203987,49.113262,48.892605,0.462987,...,0.097744,2023,9,3.878685,2.575661,8.089660,1.995872,1.660,34.477687,-0.630
5,2023-10-02,44.648651,45.040479,43.730392,43.898888,433298000,43.369469,42.960697,43.659606,0.880586,...,-0.108712,2023,10,3.798824,2.482404,7.793038,-3.711914,-1.170,32.181533,0.280
6,2023-11-01,42.198971,42.254804,40.747305,40.762260,437593000,40.658569,41.038437,41.298659,0.802494,...,-0.021850,2023,11,3.742396,2.597491,7.588279,-2.449680,1.460,28.704551,2.370
7,2023-12-01,46.625744,47.059450,46.049466,46.386461,369317000,46.630733,47.996651,47.084376,0.790057,...,0.170503,2023,12,3.842153,2.619583,7.952966,4.426773,0.300,29.547842,2.270
8,2024-01-02,48.028790,49.152531,47.457447,49.101680,411254000,49.378883,49.378883,48.928852,0.779477,...,-0.041667,2024,1,3.871801,2.462150,8.063770,1.403046,-2.000,33.761492,2.727
9,2024-02-01,62.844852,63.008380,61.471833,61.920530,369146000,61.349186,62.592579,62.262206,0.800696,...,-0.148225,2024,2,4.140669,2.504709,9.121589,14.816063,0.510,41.971640,2.845
10,2024-03-01,82.041206,82.062149,79.205424,79.768794,479135000,78.883369,77.438560,79.454379,2.353853,...,0.146848,2024,3,4.407222,2.665143,10.270782,19.196354,2.130,59.418842,3.940
11,2024-04-01,90.106079,91.962785,88.950378,90.042266,452441000,90.099106,89.993393,90.066193,0.063143,...,-0.152806,2024,4,4.500988,2.528126,10.700583,8.064873,-1.840,62.229530,3.724
12,2024-05-01,82.804878,85.755464,81.023954,84.835092,559863000,86.156334,87.507477,85.489563,2.421166,...,-0.130511,2024,5,4.416487,2.693951,10.312641,-7.301201,2.260,53.986319,4.844
13,2024-06-03,114.673012,114.673012,111.684532,113.297935,438392000,109.321289,110.185814,111.393372,2.872957,...,0.179612,2024,6,4.742085,2.833801,11.871090,31.868134,2.220,75.028809,4.710
14,2024-07-01,123.956772,124.495274,118.501875,123.129062,284885500,123.198860,123.647621,123.601084,0.381093,...,-0.209430,2024,7,4.819933,2.668616,12.270109,9.283760,-2.590,81.673550,3.670
15,2024-08-01,108.908432,119.828200,106.515058,117.205457,523462300,116.696854,103.443558,109.682948,6.660508,...,-0.043524,2024,8,4.690507,2.903617,11.612513,-15.048340,3.820,62.543739,6.760
16,2024-09-03,107.701767,115.889095,106.993728,115.689650,477155100,119.040375,117.265289,114.669144,6.098851,...,0.018153,2024,9,4.679366,2.948116,11.557253,-1.206665,0.830,59.341202,5.930
17,2024-10-01,116.686905,122.112350,115.480144,121.444137,302094500,121.115021,121.075127,119.625684,2.545136,...,-0.095606,2024,10,4.759494,2.930127,11.959405,8.985138,-0.340,72.038254,6.760
18,2024-11-01,135.037659,136.942551,134.209893,134.339535,207127800,132.404739,138.967117,135.469838,3.302467,...,-0.027243,2024,11,4.905554,3.030617,12.721404,18.350754,1.980,92.838688,7.280
19,2024-12-02,138.259048,140.074170,137.451218,138.458510,171682800,137.880051,134.977814,137.038971,1.795045,...,0.278679,2024,12,4.929129,3.058237,12.848003,3.221390,0.580,91.633305,7.560
20,2025-01-02,137.949371,138.517892,134.278974,135.645397,198247200,133.939865,137.131516,136.340251,2.118634,...,-0.076539,2025,1,4.926887,2.812410,12.835918,-0.309677,-4.640,89.920582,4.920
21,2025-02-03,116.355827,118.260843,112.715343,114.450804,371235700,119.756935,124.324989,120.145917,3.998796,...,-0.129406,2025,2,4.756653,2.892037,11.944956,-21.593544,1.380,53.510975,5.790
22,2025-03-03,113.762604,123.377468,111.987246,123.187969,411381400,124.594284,119.836731,119.397873,5.429159,...,0.287135,2025,3,4.734114,3.030617,11.830831,-2.593224,2.680,31.721397,6.340
23,2025-04-01,109.872902,109.922772,106.202159,108.246998,222614000,108.107353,109.394112,109.124789,0.913067,...,-0.133549,2025,4,4.699324,2.778198,11.656393,-3.889702,-4.620,19.766823,3.560
24,2025-05-01,111.329231,114.650856,111.020014,112.795535,236121500,108.645996,108.745743,109.573657,1.521190,...,-0.105922,2025,5,4.712492,2.921547,11.722172,1.456329,2.480,28.524353,3.780
25,2025-06-02,137.034424,137.772553,135.059394,135.149179,197663100,134.790070,138.839844,136.888112,2.028848,...,-0.004792,2025,6,4.920232,3.033510,12.800107,25.705193,2.200,22.361412,3.760
26,2025-07-01,152.924988,156.815441,151.119418,155.907664,213143600,157.603516,157.364090,155.964198,2.634754,...,-0.025677,2025,7,5.029948,3.038313,13.401055,15.890564,0.100,28.968216,6.450
27,2025-08-01,173.295029,176.108122,170.471950,173.664119,204529000,177.434875,178.831451,176.520452,2.879257,...,-0.148310,2025,8,5.154996,3.064325,14.114036,20.370041,0.550,64.386597,3.180
28,2025-09-02,170.362198,171.958290,166.810910,169.584107,231164900,173.753891,179.729248,174.615112,4.742540,...,0.066130,2025,9,5.137927,3.224858,14.014911,-2.932831,3.730,62.660431,6.080
29,2025-10-01,186.792480,187.690323,183.460452,184.797261,173844900,186.134064,181.415359,184.780635,2.932948,...,-0.090594,2025,10,5.229998,3.160823,14.556529,16.430283,-1.560,70.105576,4.860
30,2025-11-03,206.385544,210.834876,205.068691,207.582673,180267300,202.006042,202.405060,203.598882,2.421553,...,-0.095852,2025,11,5.329746,3.255786,15.162863,19.593063,2.350,71.347885,5.230
31,2025-12-01,179.489975,179.869072,173.264884,174.342304,188131000,176.576965,179.829163,178.632034,1.787804,...,0.164840,2025,12,5.190119,3.356549,14.319844,-26.895569,2.750,41.230927,7.400
32,2026-01-02,188.409134,192.479596,187.820500,189.396813,148240500,186.064606,187.102173,187.191971,1.174841,...,-0.319613,2026,1,5.238616,3.203965,14.608101,8.919159,-4.060,50.459763,7.980
33,2026-02-02,185.176682,189.855735,184.448390,186.762966,165794100,190.683807,192.060577,189.307022,3.642617,...,-0.108374,2026,2,5.221310,3.589059,14.504691,-3.232452,11.570,68.820854,18.170
34,2026-03-02,182.053986,183.031709,174.232292,174.601424,209095300,176.776352,184.458374,181.096237,3.929545,...,-0.028476,2026,3,5.204303,3.703768,14.403657,-3.122696,4.400,68.291382,19.890

In [6]:
df.index= pd.date_range(start='2023-05-01', periods=len(df), freq='M')
df = df[['Value']]
df

             Value
2023-05-31   9.946
2023-06-30  12.300
2023-07-31  10.750
2023-08-31  11.480
2023-09-30  13.140
2023-10-31  11.970
2023-11-30  13.430
2023-12-31  13.730
2024-01-31  11.730
2024-02-29  12.240
2024-03-31  14.370
2024-04-30  12.530
2024-05-31  14.790
2024-06-30  17.010
2024-07-31  14.420
2024-08-31  18.240
2024-09-30  19.070
2024-10-31  18.730
2024-11-30  20.710
2024-12-31  21.290
2025-01-31  16.650
2025-02-28  18.030
2025-03-31  20.710
2025-04-30  16.090
2025-05-31  18.570
2025-06-30  20.770
2025-07-31  20.870
2025-08-31  21.420
2025-09-30  25.150
2025-10-31  23.590
2025-11-30  25.940
2025-12-31  28.690
2026-01-31  24.630
2026-02-28  36.200
2026-03-31  40.600

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 35 entries, 2023-05-31 to 2026-03-31
Freq: M
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Value   35 non-null     float64
dtypes: float64(1)
memory usage: 560.0 bytes

In [31]:
# 3. Resample (e.g., daily 'D' or monthly 'ME') and apply an aggregation like .mean() or .sum()
df_resampled = df.resample('M').mean()

In [32]:
df_resampled

             Value
2023-05-31   9.946
2023-06-30  12.300
2023-07-31  10.750
2023-08-31  11.480
2023-09-30  13.140
2023-10-31  11.970
2023-11-30  13.430
2023-12-31  13.730
2024-01-31  11.730
2024-02-29  12.240
2024-03-31  14.370
2024-04-30  12.530
2024-05-31  14.790
2024-06-30  17.010
2024-07-31  14.420
2024-08-31  18.240
2024-09-30  19.070
2024-10-31  18.730
2024-11-30  20.710
2024-12-31  21.290
2025-01-31  16.650
2025-02-28  18.030
2025-03-31  20.710
2025-04-30  16.090
2025-05-31  18.570
2025-06-30  20.770
2025-07-31  20.870
2025-08-31  21.420
2025-09-30  25.150
2025-10-31  23.590
2025-11-30  25.940
2025-12-31  28.690
2026-01-31  24.630
2026-02-28  36.200
2026-03-31  40.600

In [33]:
df_resampled['Value'].ffill()

2023-05-31     9.946
2023-06-30    12.300
2023-07-31    10.750
2023-08-31    11.480
2023-09-30    13.140
2023-10-31    11.970
2023-11-30    13.430
2023-12-31    13.730
2024-01-31    11.730
2024-02-29    12.240
2024-03-31    14.370
2024-04-30    12.530
2024-05-31    14.790
2024-06-30    17.010
2024-07-31    14.420
2024-08-31    18.240
2024-09-30    19.070
2024-10-31    18.730
2024-11-30    20.710
2024-12-31    21.290
2025-01-31    16.650
2025-02-28    18.030
2025-03-31    20.710
2025-04-30    16.090
2025-05-31    18.570
2025-06-30    20.770
2025-07-31    20.870
2025-08-31    21.420
2025-09-30    25.150
2025-10-31    23.590
2025-11-30    25.940
2025-12-31    28.690
2026-01-31    24.630
2026-02-28    36.200
2026-03-31    40.600
Freq: M, Name: Value, dtype: float64

In [34]:
df_resampled['Value'] = df_resampled['Value'].ffill()

In [35]:
df_resampled['Value'].isna().sum()

0

In [36]:
df_resampled['Value']

2023-05-31     9.946
2023-06-30    12.300
2023-07-31    10.750
2023-08-31    11.480
2023-09-30    13.140
2023-10-31    11.970
2023-11-30    13.430
2023-12-31    13.730
2024-01-31    11.730
2024-02-29    12.240
2024-03-31    14.370
2024-04-30    12.530
2024-05-31    14.790
2024-06-30    17.010
2024-07-31    14.420
2024-08-31    18.240
2024-09-30    19.070
2024-10-31    18.730
2024-11-30    20.710
2024-12-31    21.290
2025-01-31    16.650
2025-02-28    18.030
2025-03-31    20.710
2025-04-30    16.090
2025-05-31    18.570
2025-06-30    20.770
2025-07-31    20.870
2025-08-31    21.420
2025-09-30    25.150
2025-10-31    23.590
2025-11-30    25.940
2025-12-31    28.690
2026-01-31    24.630
2026-02-28    36.200
2026-03-31    40.600
Freq: M, Name: Value, dtype: float64

In [38]:
from pycaret.time_series import TSForecastingExperiment

# 1. Load your data (Ensure index is a DatetimeIndex or PeriodIndex with correct frequency)


# 2. Instantiate and setup the experiment
# 2. Instantiate and setup the experiment
exp = TSForecastingExperiment()
exp.setup(
    data=df_resampled,
    target='Value',
    fh=6,
    fold=3,
    seasonal_period=12,
    session_id=123
)

In [40]:
# 4. Compare available models to select the top performer
# PyCaret evaluates models using metrics like MASE, RMSE, and MAPE
best_model = exp.compare_models()

# 5. Optional: Tune the selected best model to optimize hyperparameters
tuned_model = exp.tune_model(best_model)

# 6. Generate predictions for the next 12 months
future_forecast = exp.predict_model(tuned_model)
print("\n--- 6-Month Forecast ---")
print(future_forecast)

# 7. Finalize and save the model for deployment
final_model = exp.finalize_model(tuned_model)
exp.save_model(final_model, 'my_sales_forecast_model')

Fitting 3 folds for each of 1 candidates, totalling 3 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    0.0s finished

--- 6-Month Forecast ---
          y_pred
2025-10  24.0459
2025-11  24.2585
2025-12  24.4711
2026-01  24.6838
2026-02  24.8964
2026-03  25.1090
Transformation Pipeline and Model Successfully Saved

(ForecastingPipeline(steps=[('forecaster',
                             TransformedTargetForecaster(steps=[('model',
                                                                 ForecastingPipeline(steps=[('forecaster',
                                                                                             TransformedTargetForecaster(steps=[('model',
                                                                                                                                 ThetaForecaster())]))]))]))]),
 'my_sales_forecast_model.pkl')